# Generated by Django 4.2.6 on 2023-10-30 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('салаты и закуски', 'Салаты и закуски'), ('супы', 'Супы'), ('вторые блюда. мясо', 'Вторые блюда. Мясо'), ('вторые блюда. птица', 'Вторые блюда. Птица'), ('вторые блюда. рыба и морепродукты', 'Вторые блюда. Рыба и морепродукты'), ('гарниры и соусы', 'Гарниры и соусы'), ('хлеб и выпечка', 'Хлеб и выпечка'), ('десерты', 'Десерты'), ('напитки. алкоголь', 'Напитки. Алкоголь'), ('напитки. без алкоголя', 'Напитки. Без алкоголя')], max_length=50, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('steps', models.CharField(max_length=500, verbose_name='Этапы приготовления')),
                ('cooking_time', models.IntegerField(verbose_name='Время приготовления, мин')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото блюда')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Время публикации')),
            ],
        ),
        migrations.CreateModel(
            name='CookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrecipe.category')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrecipe.recipe')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
