# Generated by Django 4.2.6 on 2023-10-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipe', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.CharField(max_length=10000, verbose_name='Этапы приготовления'),
        ),
    ]
